INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("OH NO", "WHATTT", 100000000, 1, 5 );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("OH NO", "WHATTT", 100000000, 1, 5 );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("OH NO", "WHATTT", 100000000, 1, 5 );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("OH NO", "WHATTT", 100000000, 1, 5 );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("OH NO", "WHATTT", 100000000, 1, 5 );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("OH NO", "WHATTT", 100000000, 1, 5 );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("OH NO", "WHATTT", 100000000, 1, 5 );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("OH NO", "WHATTT", 100000000, 1, 5 );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("OH NO", "WHATTT", 100000000, 1, 5 );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("OH NO", "WHATTT", 100000000, 1, 5 );

INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);
INSERT INTO users (name, age) VALUES ("RYAN", 99);

INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 1, 1);
